/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r3 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w32,
    w31,
    w248,
    w217,
    w279,
    w128,
    w151,
    w4,
    w35,
    w67,
    w1024,
    w989,
    w1120,
    w1155,
    w2240,
    w2023,
    w536,
    w753,
    w2151,
    w2310,
    w2311,
    w2048,
    w3203,
    w268,
    w2419,
    w4199,
    w2416,
    w1783,
    w8960,
    w4761,
    w1208,
    w5407,
    w6024,
    w6059,
    w6812,
    w1703,
    w9522,
    w3463,
    w134,
    w5925,
    w9244,
    w15303,
    w15304,
    w1913,
    w7936,
    w7367,
    w8092,
    w604,
    w604_,
    w2310_,
    w4464,
    w1703_,
    w6406,
    w6406_,
    w2144,
    w2144_,
    w434,
    w5407_,
    w7367_,
    w7912,
    w7912_,
    w4622,
    w6926,
    w1913_,
    w3012,
    w3012_,
    w4838;

  assign w1 = X;
  assign w32 = w1 << 5;
  assign w31 = w32 - w1;
  assign w248 = w31 << 3;
  assign w217 = w248 - w31;
  assign w279 = w31 + w248;
  assign w128 = w1 << 7;
  assign w151 = w279 - w128;
  assign w4 = w1 << 2;
  assign w35 = w31 + w4;
  assign w67 = w35 + w32;
  assign w1024 = w1 << 10;
  assign w989 = w1024 - w35;
  assign w1120 = w35 << 5;
  assign w1155 = w35 + w1120;
  assign w2240 = w35 << 6;
  assign w2023 = w2240 - w217;
  assign w536 = w67 << 3;
  assign w753 = w217 + w536;
  assign w2151 = w2023 + w128;
  assign w2310 = w1155 << 1;
  assign w2311 = w1 + w2310;
  assign w2048 = w1 << 11;
  assign w3203 = w1155 + w2048;
  assign w268 = w67 << 2;
  assign w2419 = w2151 + w268;
  assign w4199 = w2151 + w2048;
  assign w2416 = w151 << 4;
  assign w1783 = w4199 - w2416;
  assign w8960 = w35 << 8;
  assign w4761 = w8960 - w4199;
  assign w1208 = w151 << 3;
  assign w5407 = w4199 + w1208;
  assign w6024 = w753 << 3;
  assign w6059 = w35 + w6024;
  assign w6812 = w753 + w6059;
  assign w1703 = w6812 >> 2;
  assign w9522 = w4761 << 1;
  assign w3463 = w9522 - w6059;
  assign w134 = w67 << 1;
  assign w5925 = w6059 - w134;
  assign w9244 = w2311 << 2;
  assign w15303 = w6059 + w9244;
  assign w15304 = w1 + w15303;
  assign w1913 = w15304 >> 3;
  assign w7936 = w31 << 8;
  assign w7367 = w15303 - w7936;
  assign w8092 = w2023 << 2;
  assign w604 = w151 << 2;
  assign w604_ = -1 * w604;
  assign w2310_ = -1 * w2310;
  assign w4464 = w279 << 4;
  assign w1703_ = -1 * w1703;
  assign w6406 = w3203 << 1;
  assign w6406_ = -1 * w6406;
  assign w2144 = w67 << 5;
  assign w2144_ = -1 * w2144;
  assign w434 = w217 << 1;
  assign w5407_ = -1 * w5407;
  assign w7367_ = -1 * w7367;
  assign w7912 = w989 << 3;
  assign w7912_ = -1 * w7912;
  assign w4622 = w2311 << 1;
  assign w6926 = w3463 << 1;
  assign w1913_ = -1 * w1913;
  assign w3012 = w753 << 2;
  assign w3012_ = -1 * w3012;
  assign w4838 = w2419 << 1;

  assign Y[0] = w8092[46:15];
  assign Y[1] = w604_[46:15];
  assign Y[2] = w4761[46:15];
  assign Y[3] = w2310_[46:15];
  assign Y[4] = w4464[46:15];
  assign Y[5] = w1703_[46:15];
  assign Y[6] = w6406_[46:15];
  assign Y[7] = w2144_[46:15];
  assign Y[8] = w434[46:15];
  assign Y[9] = w5407_[46:15];
  assign Y[10] = w7367_[46:15];
  assign Y[11] = w7912_[46:15];
  assign Y[12] = w4622[46:15];
  assign Y[13] = w6926[46:15];
  assign Y[14] = w1783[46:15];
  assign Y[15] = w1913_[46:15];
  assign Y[16] = w3012_[46:15];
  assign Y[17] = w5925[46:15];
  assign Y[18] = w2151[46:15];
  assign Y[19] = w4838[46:15];

endmodule //multiplier_block
