/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r15 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w16,
    w17,
    w136,
    w135,
    w34,
    w169,
    w338,
    w339,
    w1352,
    w1487,
    w2704,
    w2873,
    w2160,
    w673,
    w1080,
    w1793,
    w8192,
    w8531,
    w2692,
    w2709,
    w5418,
    w3931,
    w32,
    w201,
    w8,
    w209,
    w1346,
    w1547,
    w1356,
    w1557,
    w1519,
    w3038,
    w893,
    w3021,
    w3586,
    w5105,
    w12084,
    w12085,
    w14288,
    w2203,
    w21632,
    w9547,
    w2186,
    w1093,
    w2449,
    w4372,
    w5859,
    w10210,
    w10210_,
    w678,
    w678_,
    w1487_,
    w2873_,
    w540,
    w540_,
    w4096,
    w3344,
    w3344_,
    w2203_,
    w1547_,
    w3931_,
    w893_,
    w3114,
    w3114_,
    w2449_,
    w5859_;

  assign w1 = X;
  assign w16 = w1 << 4;
  assign w17 = w1 + w16;
  assign w136 = w17 << 3;
  assign w135 = w136 - w1;
  assign w34 = w17 << 1;
  assign w169 = w135 + w34;
  assign w338 = w169 << 1;
  assign w339 = w1 + w338;
  assign w1352 = w169 << 3;
  assign w1487 = w135 + w1352;
  assign w2704 = w169 << 4;
  assign w2873 = w169 + w2704;
  assign w2160 = w135 << 4;
  assign w673 = w2160 - w1487;
  assign w1080 = w135 << 3;
  assign w1793 = w2873 - w1080;
  assign w8192 = w1 << 13;
  assign w8531 = w339 + w8192;
  assign w2692 = w673 << 2;
  assign w2709 = w17 + w2692;
  assign w5418 = w2709 << 1;
  assign w3931 = w5418 - w1487;
  assign w32 = w1 << 5;
  assign w201 = w169 + w32;
  assign w8 = w1 << 3;
  assign w209 = w201 + w8;
  assign w1346 = w673 << 1;
  assign w1547 = w201 + w1346;
  assign w1356 = w339 << 2;
  assign w1557 = w201 + w1356;
  assign w1519 = w1487 + w32;
  assign w3038 = w1519 << 1;
  assign w893 = w3931 - w3038;
  assign w3021 = w3038 - w17;
  assign w3586 = w1793 << 1;
  assign w5105 = w1519 + w3586;
  assign w12084 = w3021 << 2;
  assign w12085 = w1 + w12084;
  assign w14288 = w893 << 4;
  assign w2203 = w14288 - w12085;
  assign w21632 = w169 << 7;
  assign w9547 = w21632 - w12085;
  assign w2186 = w2203 - w17;
  assign w1093 = w2186 >> 1;
  assign w2449 = w1093 + w1356;
  assign w4372 = w1093 << 2;
  assign w5859 = w1487 + w4372;
  assign w10210 = w5105 << 1;
  assign w10210_ = -1 * w10210;
  assign w678 = w339 << 1;
  assign w678_ = -1 * w678;
  assign w1487_ = -1 * w1487;
  assign w2873_ = -1 * w2873;
  assign w540 = w135 << 2;
  assign w540_ = -1 * w540;
  assign w4096 = w1 << 12;
  assign w3344 = w209 << 4;
  assign w3344_ = -1 * w3344;
  assign w2203_ = -1 * w2203;
  assign w1547_ = -1 * w1547;
  assign w3931_ = -1 * w3931;
  assign w893_ = -1 * w893;
  assign w3114 = w1557 << 1;
  assign w3114_ = -1 * w3114;
  assign w2449_ = -1 * w2449;
  assign w5859_ = -1 * w5859;

  assign Y[0] = w10210_[46:15];
  assign Y[1] = w678_[46:15];
  assign Y[2] = w1487_[46:15];
  assign Y[3] = w2873_[46:15];
  assign Y[4] = w540_[46:15];
  assign Y[5] = w4096[46:15];
  assign Y[6] = w3344_[46:15];
  assign Y[7] = w9547[46:15];
  assign Y[8] = w2203_[46:15];
  assign Y[9] = w1346[46:15];
  assign Y[10] = w1547_[46:15];
  assign Y[11] = w8531[46:15];
  assign Y[12] = w3931_[46:15];
  assign Y[13] = w893_[46:15];
  assign Y[14] = w3586[46:15];
  assign Y[15] = w3021[46:15];
  assign Y[16] = w3114_[46:15];
  assign Y[17] = w2709[46:15];
  assign Y[18] = w2449_[46:15];
  assign Y[19] = w5859_[46:15];

endmodule //multiplier_block
