/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r12 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w4,
    w5,
    w40,
    w45,
    w80,
    w75,
    w640,
    w635,
    w2400,
    w3035,
    w5120,
    w2085,
    w20,
    w2065,
    w2,
    w2087,
    w4170,
    w4215,
    w3,
    w384,
    w387,
    w2449,
    w12,
    w4227,
    w6144,
    w8229,
    w4800,
    w4413,
    w8430,
    w5395,
    w4096,
    w1299,
    w7844,
    w1961,
    w7482,
    w3741,
    w96,
    w95,
    w760,
    w373,
    w4635,
    w4705,
    w1270,
    w1270_,
    w8348,
    w8826,
    w8826_,
    w2449_,
    w1299_,
    w8229_,
    w4705_,
    w2085_,
    w2984,
    w2984_,
    w5760,
    w3741_,
    w6192,
    w6192_,
    w3922;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w40 = w5 << 3;
  assign w45 = w5 + w40;
  assign w80 = w5 << 4;
  assign w75 = w80 - w5;
  assign w640 = w5 << 7;
  assign w635 = w640 - w5;
  assign w2400 = w75 << 5;
  assign w3035 = w635 + w2400;
  assign w5120 = w5 << 10;
  assign w2085 = w5120 - w3035;
  assign w20 = w5 << 2;
  assign w2065 = w2085 - w20;
  assign w2 = w1 << 1;
  assign w2087 = w2085 + w2;
  assign w4170 = w2085 << 1;
  assign w4215 = w45 + w4170;
  assign w3 = w4 - w1;
  assign w384 = w3 << 7;
  assign w387 = w3 + w384;
  assign w2449 = w2065 + w384;
  assign w12 = w3 << 2;
  assign w4227 = w4215 + w12;
  assign w6144 = w3 << 11;
  assign w8229 = w2085 + w6144;
  assign w4800 = w75 << 6;
  assign w4413 = w4800 - w387;
  assign w8430 = w4215 << 1;
  assign w5395 = w8430 - w3035;
  assign w4096 = w1 << 12;
  assign w1299 = w5395 - w4096;
  assign w7844 = w2449 + w5395;
  assign w1961 = w7844 >> 2;
  assign w7482 = w2087 + w5395;
  assign w3741 = w7482 >> 1;
  assign w96 = w3 << 5;
  assign w95 = w96 - w1;
  assign w760 = w95 << 3;
  assign w373 = w760 - w387;
  assign w4635 = w5395 - w760;
  assign w4705 = w4800 - w95;
  assign w1270 = w635 << 1;
  assign w1270_ = -1 * w1270;
  assign w8348 = w2087 << 2;
  assign w8826 = w4413 << 1;
  assign w8826_ = -1 * w8826;
  assign w2449_ = -1 * w2449;
  assign w1299_ = -1 * w1299;
  assign w8229_ = -1 * w8229;
  assign w4705_ = -1 * w4705;
  assign w2085_ = -1 * w2085;
  assign w2984 = w373 << 3;
  assign w2984_ = -1 * w2984;
  assign w5760 = w45 << 7;
  assign w3741_ = -1 * w3741;
  assign w6192 = w387 << 4;
  assign w6192_ = -1 * w6192;
  assign w3922 = w1961 << 1;

  assign Y[0] = w5120[46:15];
  assign Y[1] = w1270_[46:15];
  assign Y[2] = w4635[46:15];
  assign Y[3] = w8348[46:15];
  assign Y[4] = w8826_[46:15];
  assign Y[5] = w4215[46:15];
  assign Y[6] = w2449_[46:15];
  assign Y[7] = w75[46:15];
  assign Y[8] = w1299_[46:15];
  assign Y[9] = w8229_[46:15];
  assign Y[10] = w4705_[46:15];
  assign Y[11] = w2085_[46:15];
  assign Y[12] = w2984_[46:15];
  assign Y[13] = w2065[46:15];
  assign Y[14] = w5760[46:15];
  assign Y[15] = w3741_[46:15];
  assign Y[16] = w4227[46:15];
  assign Y[17] = w3035[46:15];
  assign Y[18] = w6192_[46:15];
  assign Y[19] = w3922[46:15];

endmodule //multiplier_block
