/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r6 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w8,
    w7,
    w1024,
    w1031,
    w28,
    w21,
    w42,
    w989,
    w2688,
    w3719,
    w224,
    w1213,
    w2,
    w3721,
    w2048,
    w835,
    w3956,
    w237,
    w56,
    w181,
    w112,
    w349,
    w3792,
    w2579,
    w4781,
    w356,
    w89,
    w2572,
    w643,
    w7442,
    w6411,
    w10288,
    w3877,
    w84,
    w6327,
    w14,
    w6425,
    w64,
    w3941,
    w1344,
    w5221,
    w2792,
    w9217,
    w1071,
    w10430,
    w5215,
    w5696,
    w14913,
    w7438,
    w7475,
    w712,
    w7438_,
    w5144,
    w698,
    w698_,
    w835_,
    w5221_,
    w2579_,
    w6425_,
    w4852,
    w3877_,
    w5215_,
    w724;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w1024 = w1 << 10;
  assign w1031 = w7 + w1024;
  assign w28 = w7 << 2;
  assign w21 = w28 - w7;
  assign w42 = w21 << 1;
  assign w989 = w1031 - w42;
  assign w2688 = w21 << 7;
  assign w3719 = w1031 + w2688;
  assign w224 = w7 << 5;
  assign w1213 = w989 + w224;
  assign w2 = w1 << 1;
  assign w3721 = w3719 + w2;
  assign w2048 = w1 << 11;
  assign w835 = w2048 - w1213;
  assign w3956 = w989 << 2;
  assign w237 = w3956 - w3719;
  assign w56 = w7 << 3;
  assign w181 = w237 - w56;
  assign w112 = w7 << 4;
  assign w349 = w237 + w112;
  assign w3792 = w237 << 4;
  assign w2579 = w3792 - w1213;
  assign w4781 = w989 + w3792;
  assign w356 = w7 + w349;
  assign w89 = w356 >> 2;
  assign w2572 = w2579 - w7;
  assign w643 = w2572 >> 2;
  assign w7442 = w3721 << 1;
  assign w6411 = w7442 - w1031;
  assign w10288 = w643 << 4;
  assign w3877 = w10288 - w6411;
  assign w84 = w21 << 2;
  assign w6327 = w6411 - w84;
  assign w14 = w7 << 1;
  assign w6425 = w6411 + w14;
  assign w64 = w1 << 6;
  assign w3941 = w3877 + w64;
  assign w1344 = w21 << 6;
  assign w5221 = w3877 + w1344;
  assign w2792 = w349 << 3;
  assign w9217 = w6425 + w2792;
  assign w1071 = w10288 - w9217;
  assign w10430 = w1213 + w9217;
  assign w5215 = w10430 >> 1;
  assign w5696 = w89 << 6;
  assign w14913 = w9217 + w5696;
  assign w7438 = w3719 << 1;
  assign w7475 = w14913 - w7438;
  assign w712 = w89 << 3;
  assign w7438_ = -1 * w7438;
  assign w5144 = w643 << 3;
  assign w698 = w349 << 1;
  assign w698_ = -1 * w698;
  assign w835_ = -1 * w835;
  assign w5221_ = -1 * w5221;
  assign w2579_ = -1 * w2579;
  assign w6425_ = -1 * w6425;
  assign w4852 = w1213 << 2;
  assign w3877_ = -1 * w3877;
  assign w5215_ = -1 * w5215;
  assign w724 = w181 << 2;

  assign Y[0] = w712[46:15];
  assign Y[1] = w989[46:15];
  assign Y[2] = w7438_[46:15];
  assign Y[3] = w1071[46:15];
  assign Y[4] = w3941[46:15];
  assign Y[5] = w1031[46:15];
  assign Y[6] = w5144[46:15];
  assign Y[7] = w698_[46:15];
  assign Y[8] = w6327[46:15];
  assign Y[9] = w835_[46:15];
  assign Y[10] = w5221_[46:15];
  assign Y[11] = w3721[46:15];
  assign Y[12] = w2579_[46:15];
  assign Y[13] = w6425_[46:15];
  assign Y[14] = w4852[46:15];
  assign Y[15] = w3877_[46:15];
  assign Y[16] = w5215_[46:15];
  assign Y[17] = w724[46:15];
  assign Y[18] = w4781[46:15];
  assign Y[19] = w7475[46:15];

endmodule //multiplier_block

