/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r4 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w32,
    w33,
    w256,
    w223,
    w4,
    w37,
    w74,
    w73,
    w446,
    w409,
    w77,
    w264,
    w187,
    w154,
    w563,
    w1232,
    w1199,
    w3272,
    w3349,
    w633,
    w748,
    w971,
    w4736,
    w5369,
    w892,
    w4477,
    w5523,
    w1056,
    w6425,
    w8954,
    w9177,
    w5984,
    w3193,
    w4441,
    w3884,
    w5293,
    w3549,
    w8448,
    w12889,
    w14272,
    w1383,
    w6544,
    w6345,
    w13396,
    w14029,
    w10680,
    w1335,
    w1942,
    w1942_,
    w3568,
    w3568_,
    w4477_,
    w1266,
    w1266_,
    w584,
    w6386,
    w4796,
    w6425_,
    w1383_,
    w5523_,
    w2992,
    w2992_,
    w3549_,
    w1335_,
    w563_;

  assign w1 = X;
  assign w32 = w1 << 5;
  assign w33 = w1 + w32;
  assign w256 = w1 << 8;
  assign w223 = w256 - w33;
  assign w4 = w1 << 2;
  assign w37 = w33 + w4;
  assign w74 = w37 << 1;
  assign w73 = w74 - w1;
  assign w446 = w223 << 1;
  assign w409 = w446 - w37;
  assign w77 = w73 + w4;
  assign w264 = w33 << 3;
  assign w187 = w264 - w77;
  assign w154 = w77 << 1;
  assign w563 = w409 + w154;
  assign w1232 = w77 << 4;
  assign w1199 = w1232 - w33;
  assign w3272 = w409 << 3;
  assign w3349 = w77 + w3272;
  assign w633 = w187 + w446;
  assign w748 = w187 << 2;
  assign w971 = w223 + w748;
  assign w4736 = w37 << 7;
  assign w5369 = w633 + w4736;
  assign w892 = w223 << 2;
  assign w4477 = w5369 - w892;
  assign w5523 = w5369 + w154;
  assign w1056 = w33 << 5;
  assign w6425 = w5369 + w1056;
  assign w8954 = w4477 << 1;
  assign w9177 = w223 + w8954;
  assign w5984 = w187 << 5;
  assign w3193 = w9177 - w5984;
  assign w4441 = w9177 - w4736;
  assign w3884 = w971 << 2;
  assign w5293 = w9177 - w3884;
  assign w3549 = w4441 - w892;
  assign w8448 = w33 << 8;
  assign w12889 = w4441 + w8448;
  assign w14272 = w223 << 6;
  assign w1383 = w14272 - w12889;
  assign w6544 = w409 << 4;
  assign w6345 = w12889 - w6544;
  assign w13396 = w3349 << 2;
  assign w14029 = w633 + w13396;
  assign w10680 = w14029 - w3349;
  assign w1335 = w10680 >> 3;
  assign w1942 = w971 << 1;
  assign w1942_ = -1 * w1942;
  assign w3568 = w223 << 4;
  assign w3568_ = -1 * w3568;
  assign w4477_ = -1 * w4477;
  assign w1266 = w633 << 1;
  assign w1266_ = -1 * w1266;
  assign w584 = w73 << 3;
  assign w6386 = w3193 << 1;
  assign w4796 = w1199 << 2;
  assign w6425_ = -1 * w6425;
  assign w1383_ = -1 * w1383;
  assign w5523_ = -1 * w5523;
  assign w2992 = w187 << 4;
  assign w2992_ = -1 * w2992;
  assign w3549_ = -1 * w3549;
  assign w1335_ = -1 * w1335;
  assign w563_ = -1 * w563;

  assign Y[0] = w1942_[46:15];
  assign Y[1] = w6345[46:15];
  assign Y[2] = w3568_[46:15];
  assign Y[3] = w4477_[46:15];
  assign Y[4] = w3272[46:15];
  assign Y[5] = w1266_[46:15];
  assign Y[6] = w584[46:15];
  assign Y[7] = w4441[46:15];
  assign Y[8] = w6386[46:15];
  assign Y[9] = w4796[46:15];
  assign Y[10] = w6425_[46:15];
  assign Y[11] = w4477[46:15];
  assign Y[12] = w3349[46:15];
  assign Y[13] = w1383_[46:15];
  assign Y[14] = w5523_[46:15];
  assign Y[15] = w2992_[46:15];
  assign Y[16] = w5293[46:15];
  assign Y[17] = w3549_[46:15];
  assign Y[18] = w1335_[46:15];
  assign Y[19] = w563_[46:15];

endmodule //multiplier_block
