/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r10 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w4,
    w3,
    w24,
    w21,
    w32,
    w31,
    w124,
    w145,
    w384,
    w415,
    w496,
    w493,
    w1984,
    w1983,
    w6,
    w487,
    w1344,
    w1489,
    w84,
    w1573,
    w96,
    w1669,
    w1665,
    w3338,
    w2845,
    w12,
    w133,
    w3072,
    w2939,
    w3320,
    w3187,
    w532,
    w3377,
    w3968,
    w4101,
    w53,
    w848,
    w433,
    w212,
    w3057,
    w1696,
    w4541,
    w3392,
    w4881,
    w1732,
    w1763,
    w493_,
    w3146,
    w7792,
    w7792_,
    w8202,
    w6676,
    w4881_,
    w3320_,
    w5878,
    w3966,
    w3966_,
    w3526,
    w42,
    w42_,
    w3330,
    w3330_,
    w3057_,
    w6754,
    w6754_,
    w6928,
    w2978;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w3 = w4 - w1;
  assign w24 = w3 << 3;
  assign w21 = w24 - w3;
  assign w32 = w1 << 5;
  assign w31 = w32 - w1;
  assign w124 = w31 << 2;
  assign w145 = w21 + w124;
  assign w384 = w3 << 7;
  assign w415 = w31 + w384;
  assign w496 = w31 << 4;
  assign w493 = w496 - w3;
  assign w1984 = w31 << 6;
  assign w1983 = w1984 - w1;
  assign w6 = w3 << 1;
  assign w487 = w493 - w6;
  assign w1344 = w21 << 6;
  assign w1489 = w145 + w1344;
  assign w84 = w21 << 2;
  assign w1573 = w1489 + w84;
  assign w96 = w3 << 5;
  assign w1669 = w1573 + w96;
  assign w1665 = w1669 - w4;
  assign w3338 = w1669 << 1;
  assign w2845 = w3338 - w493;
  assign w12 = w3 << 2;
  assign w133 = w145 - w12;
  assign w3072 = w3 << 10;
  assign w2939 = w3072 - w133;
  assign w3320 = w415 << 3;
  assign w3187 = w3320 - w133;
  assign w532 = w133 << 2;
  assign w3377 = w2845 + w532;
  assign w3968 = w31 << 7;
  assign w4101 = w133 + w3968;
  assign w53 = w21 + w32;
  assign w848 = w53 << 4;
  assign w433 = w848 - w415;
  assign w212 = w53 << 2;
  assign w3057 = w2845 + w212;
  assign w1696 = w53 << 5;
  assign w4541 = w2845 + w1696;
  assign w3392 = w53 << 6;
  assign w4881 = w1489 + w3392;
  assign w1732 = w433 << 2;
  assign w1763 = w31 + w1732;
  assign w493_ = -1 * w493;
  assign w3146 = w1573 << 1;
  assign w7792 = w487 << 4;
  assign w7792_ = -1 * w7792;
  assign w8202 = w4101 << 1;
  assign w6676 = w1669 << 2;
  assign w4881_ = -1 * w4881;
  assign w3320_ = -1 * w3320;
  assign w5878 = w2939 << 1;
  assign w3966 = w1983 << 1;
  assign w3966_ = -1 * w3966;
  assign w3526 = w1763 << 1;
  assign w42 = w21 << 1;
  assign w42_ = -1 * w42;
  assign w3330 = w1665 << 1;
  assign w3330_ = -1 * w3330;
  assign w3057_ = -1 * w3057;
  assign w6754 = w3377 << 1;
  assign w6754_ = -1 * w6754;
  assign w6928 = w433 << 4;
  assign w2978 = w1489 << 1;

  assign Y[0] = w493_[46:15];
  assign Y[1] = w3146[46:15];
  assign Y[2] = w7792_[46:15];
  assign Y[3] = w8202[46:15];
  assign Y[4] = w2845[46:15];
  assign Y[5] = w6676[46:15];
  assign Y[6] = w4881_[46:15];
  assign Y[7] = w3187[46:15];
  assign Y[8] = w3320_[46:15];
  assign Y[9] = w5878[46:15];
  assign Y[10] = w4541[46:15];
  assign Y[11] = w3966_[46:15];
  assign Y[12] = w3526[46:15];
  assign Y[13] = w42_[46:15];
  assign Y[14] = w3330_[46:15];
  assign Y[15] = w145[46:15];
  assign Y[16] = w3057_[46:15];
  assign Y[17] = w6754_[46:15];
  assign Y[18] = w6928[46:15];
  assign Y[19] = w2978[46:15];

endmodule //multiplier_block

